apiVersion: v1
kind: Secret
metadata:
  name: quay-push-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbWd0WldVdFpITnZiR1J2SzNkcGJtUjBkWEppYVc1bE9sVlZURWN6TkU1RVJVMVRORE5FUkVSQlNFMVlSRWRUVms5T01WVkRSemxKUkRsU01rTlZUREpDV0VoRlVsQlJURlZFTTBWSFRsTlJORFJXV2xNelRFbz0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson