manifestsGitUrl: "https://github.com/gmodzelewski/quinoa-wind-turbine-manifests"
# manifestsGitBranch: main
applicationGitUrl: "https://github.com/gmodzelewski/quinoa-wind-turbine.git"
# pathToContainerfileInApplicationRepo: # default: ./src/main/docker/Dockerfile.jvm WIP - add mvn goals accordingly
image: "quay.io/modzelewski/quinoa-wind-turbine"
imageTag: latest # Overwrite this value in the applicationSet - wind-turbine-app.yaml
# imageDigest: sha256@xxx # Overwrite this value in the applicationSet - wind-turbine-app.yaml
# followChangesForBranch: # default: empty -> if set, tekton files get created
stage: dev # must be the name of the stage folder with the config.json
disableSecretsDeployment: false

infinispan:
  deploy:
    nameOverride: infinispan # install of dependency in a local way (because argocd only uses helm template) needs this
